$axure.loadCurrentPage({
  "url":"充值.html",
  "generationDate":new Date(1560007707641.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b835505b57ed48cc961798b6d7433f5e",
    "type":"Axure:Page",
    "name":"充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da8e9857ebb74921b1cd255b48cdcad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "location":{
              "x":254,
              "y":163},
            "size":{
              "width":596,
              "height":337}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04562ee40b742c3a581910c671ddc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "location":{
                  "x":254,
                  "y":163},
                "size":{
                  "width":596,
                  "height":337}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"2427fc2a3cc04bb7bb2fe21deb2e90aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":163},
            "size":{
              "width":238,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5445542bc99541d4a8ac52aaf4d67c8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":163},
                "size":{
                  "width":238,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.jpg"}},
{
          "id":"148f540f737f4d5d845e69c668f2c6ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":163},
            "size":{
              "width":260,
              "height":337}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5c0a0412534ef1ad81c96d5c1d517c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":566,
                  "y":163},
                "size":{
                  "width":260,
                  "height":337}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"7487fa3c3f09449084117107fc614d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":254,
              "y":503},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57596530998b43208c726565d8ff3c30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":254,
                  "y":503},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45118c1a8bd849ef9416217dc5b6c9d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":254,
              "y":544},
            "size":{
              "width":250,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"419e8ff51c994f42842d0226a59ceeef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":254,
                  "y":544},
                "size":{
                  "width":250,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccec8689e87146349f2633109add309c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"158b5a7db7814290a2f139e6f97dc4d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"45543790d7c645259915b0b26ad244ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a36d2ed202468d8a88a9ff4617d11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"84818a5fc8754960b974c7a56f66d089",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30687ea0c8c0499599a3be4317bd0a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"c7126a664f5c49d399e8133728947cb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2f37d9e942e4d60ad2b6e2f40e1449a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"88f066b92a204ff5904093b262bb424c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba499a578d1b48ad819ee304d00519cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c0d5dace48047939be3e29c337439b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"029c49ff84cb4d61bced9564b29b5ff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a7a865f35cb41869db0a4a3f54dde2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5bde57343134d59b95085dee47d3cb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81a9b6d12a374fb694c53ea09d9d1c7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64314df04b24e0cb9423dacb706ba33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b28f7cd14784443e951c9bac4a31012b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5f1605425de45ada9bd82185ce07b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u28.png"}},
{
          "id":"6402af8369d0403d8e06e4dcc46f6290",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb9557e7c5f4be7bdf67dff0112247d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"477904cb2720483aa6d02eb5d332c197",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79efecb116c44436b4941d03008ce611",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"b610a7b73c2142c3ab13aaf9f8c99646",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d45402327884237842aeefadc06f25c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "da8e9857ebb74921b1cd255b48cdcad8":{
      "scriptId":"u0"},
    "d04562ee40b742c3a581910c671ddc5e":{
      "scriptId":"u1"},
    "2427fc2a3cc04bb7bb2fe21deb2e90aa":{
      "scriptId":"u2"},
    "5445542bc99541d4a8ac52aaf4d67c8d":{
      "scriptId":"u3"},
    "148f540f737f4d5d845e69c668f2c6ec":{
      "scriptId":"u4"},
    "3a5c0a0412534ef1ad81c96d5c1d517c":{
      "scriptId":"u5"},
    "7487fa3c3f09449084117107fc614d18":{
      "scriptId":"u6"},
    "57596530998b43208c726565d8ff3c30":{
      "scriptId":"u7"},
    "45118c1a8bd849ef9416217dc5b6c9d8":{
      "scriptId":"u8"},
    "419e8ff51c994f42842d0226a59ceeef":{
      "scriptId":"u9"},
    "ccec8689e87146349f2633109add309c":{
      "scriptId":"u10"},
    "158b5a7db7814290a2f139e6f97dc4d0":{
      "scriptId":"u11"},
    "45543790d7c645259915b0b26ad244ca":{
      "scriptId":"u12"},
    "38a36d2ed202468d8a88a9ff4617d11d":{
      "scriptId":"u13"},
    "84818a5fc8754960b974c7a56f66d089":{
      "scriptId":"u14"},
    "30687ea0c8c0499599a3be4317bd0a91":{
      "scriptId":"u15"},
    "c7126a664f5c49d399e8133728947cb3":{
      "scriptId":"u16"},
    "f2f37d9e942e4d60ad2b6e2f40e1449a":{
      "scriptId":"u17"},
    "88f066b92a204ff5904093b262bb424c":{
      "scriptId":"u18"},
    "ba499a578d1b48ad819ee304d00519cb":{
      "scriptId":"u19"},
    "7c0d5dace48047939be3e29c337439b4":{
      "scriptId":"u20"},
    "029c49ff84cb4d61bced9564b29b5ff5":{
      "scriptId":"u21"},
    "0a7a865f35cb41869db0a4a3f54dde2a":{
      "scriptId":"u22"},
    "a5bde57343134d59b95085dee47d3cb3":{
      "scriptId":"u23"},
    "81a9b6d12a374fb694c53ea09d9d1c7a":{
      "scriptId":"u24"},
    "f64314df04b24e0cb9423dacb706ba33":{
      "scriptId":"u25"},
    "b28f7cd14784443e951c9bac4a31012b":{
      "scriptId":"u26"},
    "a5f1605425de45ada9bd82185ce07b49":{
      "scriptId":"u27"},
    "6402af8369d0403d8e06e4dcc46f6290":{
      "scriptId":"u28"},
    "4fb9557e7c5f4be7bdf67dff0112247d":{
      "scriptId":"u29"},
    "477904cb2720483aa6d02eb5d332c197":{
      "scriptId":"u30"},
    "79efecb116c44436b4941d03008ce611":{
      "scriptId":"u31"},
    "b610a7b73c2142c3ab13aaf9f8c99646":{
      "scriptId":"u32"},
    "9d45402327884237842aeefadc06f25c":{
      "scriptId":"u33"}}});