$axure.loadCurrentPage({
  "url":"历史信息.html",
  "generationDate":new Date(1560007707779.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08eeb1c9482e4f12b848fa167b9f89c0",
    "type":"Axure:Page",
    "name":"历史信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3915482b5bab46edbfcc79307f4bbbb2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":170},
            "size":{
              "width":616,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da42bdea21834247be0b1f9a70a18eda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ac08678babc43d6a13e7158fd1263b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"959b95dfa5a4432c8e02a480119f2893",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eaa48629fdb6447abb602c64c328ea3c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"9c697f71481b4fcc8a9e4f560255a796",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d17c82182302487192b96b0f3c75cbb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"cb87694cc4694380898ae4b9a4ec22f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23e30951aa9243bda3dc6f2e1bb65cfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"f6f11f011d2d44ce87948155aec6c163",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"449c5b5e84cc43dbbee8d6bdf867401e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"4981ede462fe4725a5d348edd9fd68bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":60},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed6483875d8b4b249883c13e4a3d1366",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"d18752f723a24cd0b738caa8de37b6bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99cb2e0ccfe940c4ba644e24a6379654",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"c6ea849e4a6c44b6b58cd3499a9e7c08",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58e62e99d4bf40c1970322358c7c052d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"3890193161ed4732ab2dad69e0b2a3be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":60},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37fac8db84e24d68b9a4e79bba405538",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"da968487b06d43609ef65c5e0dbe7b3d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"463956cfcbd0463b9a3fced1c3f2bd2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"072ed3cff1e84449a57fcf97102d231d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6626e80eb0f549df83bc8f5c3b10747f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"6691900fcfc94c318e6c2db98a6a8807",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6cbe2be51ed4f3f856210dd65fa9bc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"80c7b28678c84850ac75ae5f175a3c3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e47316dbdc54ba4a7952039ca5f7aa7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"d1abfb122c2a4fe792a108e944f2b1a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":30},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c6f05e782ff422d91dee57894292f89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":30},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"93c1a4a85ee14751b4e83a14e0e392cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":60},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4844d228cc541d2aaa2a4f6489188e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":60},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"37aa8f4abb354109b45b50b062ed7bb0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"150d601d56ca48079b545d9db92d5a44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u71.png"}},
{
              "id":"0a34164dddbc46609986d4c4d6fa2fe4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":210},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6af1b0b4d1847469dbf3b543f791919",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":210},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u71.png"}},
{
              "id":"381e893b41e040cba18abaa995c2abdc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":210},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2a1c4fc8f364428b270cdfb13d8a1ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":210},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u71.png"}},
{
              "id":"6cd6a965331c4cf5b5bcab158b8e264c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":210},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"695393fd6def43e98668274350552a2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":210},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u71.png"}},
{
              "id":"d0e7b133b44e456292f981a43826e01f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":210},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92f34dbae2924e489014c6432e35d3fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":210},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u79.png"}},
{
              "id":"77b9df02f72f4670913f710818232ff1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d23e35b2c1cc4aecb294b16ea43d4cd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"375742dc8470482199dfb07d1e86fa1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":180},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8840ed51bbb0421190c541c9edb73cdc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":180},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"26466de35cb14bc0b14b1277e9275def",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":180},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb51d4ea07f94de5b5cfc6018e716fd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":180},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"294ed49fff6548ca91d5510ebd6d55e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":180},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ebd98033fe1544dcbc988d5db0dc6f3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":180},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"5758aa998f53419cbe80bad670537209",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":180},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b620ec508fb348eeb01fb3dc51caba95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":180},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"3db59b962bd947bbaa42b0bd46a16923",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"011f454c6dcd454d98b5721ae1d47b5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"ada378a4c9714b8caf265f57480de03e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdc590800e72410998656915f86908cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":150},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"23da97126c8149c58d32f9d71f9afff3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":150},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea763d184f8c42809c172c738484acbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":150},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"c2cd169ecafb456992ef50c50a71552a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":150},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ede0e5fe6274d3ca5a7b2c9cb1e5d87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":150},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"9590e97cdffa42ec9bf0273566f026c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":150},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37dda751c87541e4aa7248cca93f2afb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":150},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"de8fdb83d92f4239849dce67cb5818a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a00c551bacb04ad1ac204468f2c5e964",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"fd46caa0c488407f9dd051d0a4057fa5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":120},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a790ea41a0a424bbe00bce110ace6d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":120},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"738b589d251b430a8232b9f9df9abf59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":120},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72a6372c78604944bb4faa8db0b8eacc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":120},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"bd090efaf5b44fafa3a3642776e313c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":120},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97b7903403864309bd97e9303bd3c17b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":120},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"b35b0f87cf6242bd99277df19dd37218",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":120},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"537ef3e93b6b41b9a834481c72162f87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":120},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}},
{
              "id":"17c260fe8de54f8a93af96baccc3d534",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46c775cc84c544e1a63fa5ebea6d7360",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"d0b6cd241f5146acac65b4967288ec1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":90},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3af7790d7f1d4481a50c57f864fb4a47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"181ef29ceee54376af0d1221d8864a8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":240,
                  "y":90},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a84ef85d973451e985c48a982b83956",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":240,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"6d33aa9b952345d18014797f9d2eca95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":360,
                  "y":90},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c985c10415e42e2afa17ceb89712b99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u1.png"}},
{
              "id":"9251db969bdd40d4a7a1c3d37f182c23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad75f623163f4f0eb5d1c2816c9eefe4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":480,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/历史信息/u9.png"}}]},
{
          "id":"5905b9ae1d8b461cba69b74cd14b7da7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b40e7168073413492bab75f46d88a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"5419a729924f423ebd6f1d9fe666358f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da16c7a386b34bb1be63f4191feaf01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"345e5a069f074d1fab996c14ec0d1b48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8104f6ae02184c8385ff06cb8ed12993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"b3a1d7b140ec428084922a0d7e8950f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4414821f0aed454989bb2bb20712f229",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"39c5ae4d707e45ee8414fb1ba03cb73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad568b775054efe8798c6da69530908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97a93b07fd3d402f9994bd2dc100705f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c964736e70bb46bfb70644c566e34965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cba0697d42b45a68e11a997f6969814",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b46eb6fd4d0449a9ce5430f1d64cb9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecb63cf44de348f4a2f65b9789855527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7188934807f415b88db3d0b7d648730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"594dfce3c6b04c34b13708f334ef1896",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41367c3f686c454991936aff27742e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u28.png"}},
{
          "id":"29dac49bdfd744da84f1ffeb687b601b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eef45ad6db04f6f8a67d606a47eaa0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9d6cd294b734b57a9a8812a8f3ca051",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20c432090cc43eb8221c019f01d2ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"e58b68824b4247339f32578d9d62e9bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4fc24c49bce4d539db169158c1f5d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3915482b5bab46edbfcc79307f4bbbb2":{
      "scriptId":"u0"},
    "da42bdea21834247be0b1f9a70a18eda":{
      "scriptId":"u1"},
    "2ac08678babc43d6a13e7158fd1263b3":{
      "scriptId":"u2"},
    "cb87694cc4694380898ae4b9a4ec22f1":{
      "scriptId":"u3"},
    "23e30951aa9243bda3dc6f2e1bb65cfd":{
      "scriptId":"u4"},
    "d18752f723a24cd0b738caa8de37b6bd":{
      "scriptId":"u5"},
    "99cb2e0ccfe940c4ba644e24a6379654":{
      "scriptId":"u6"},
    "80c7b28678c84850ac75ae5f175a3c3b":{
      "scriptId":"u7"},
    "7e47316dbdc54ba4a7952039ca5f7aa7":{
      "scriptId":"u8"},
    "da968487b06d43609ef65c5e0dbe7b3d":{
      "scriptId":"u9"},
    "463956cfcbd0463b9a3fced1c3f2bd2d":{
      "scriptId":"u10"},
    "959b95dfa5a4432c8e02a480119f2893":{
      "scriptId":"u11"},
    "eaa48629fdb6447abb602c64c328ea3c":{
      "scriptId":"u12"},
    "f6f11f011d2d44ce87948155aec6c163":{
      "scriptId":"u13"},
    "449c5b5e84cc43dbbee8d6bdf867401e":{
      "scriptId":"u14"},
    "c6ea849e4a6c44b6b58cd3499a9e7c08":{
      "scriptId":"u15"},
    "58e62e99d4bf40c1970322358c7c052d":{
      "scriptId":"u16"},
    "d1abfb122c2a4fe792a108e944f2b1a5":{
      "scriptId":"u17"},
    "1c6f05e782ff422d91dee57894292f89":{
      "scriptId":"u18"},
    "072ed3cff1e84449a57fcf97102d231d":{
      "scriptId":"u19"},
    "6626e80eb0f549df83bc8f5c3b10747f":{
      "scriptId":"u20"},
    "9c697f71481b4fcc8a9e4f560255a796":{
      "scriptId":"u21"},
    "d17c82182302487192b96b0f3c75cbb6":{
      "scriptId":"u22"},
    "4981ede462fe4725a5d348edd9fd68bc":{
      "scriptId":"u23"},
    "ed6483875d8b4b249883c13e4a3d1366":{
      "scriptId":"u24"},
    "3890193161ed4732ab2dad69e0b2a3be":{
      "scriptId":"u25"},
    "37fac8db84e24d68b9a4e79bba405538":{
      "scriptId":"u26"},
    "93c1a4a85ee14751b4e83a14e0e392cb":{
      "scriptId":"u27"},
    "f4844d228cc541d2aaa2a4f6489188e5":{
      "scriptId":"u28"},
    "6691900fcfc94c318e6c2db98a6a8807":{
      "scriptId":"u29"},
    "b6cbe2be51ed4f3f856210dd65fa9bc5":{
      "scriptId":"u30"},
    "17c260fe8de54f8a93af96baccc3d534":{
      "scriptId":"u31"},
    "46c775cc84c544e1a63fa5ebea6d7360":{
      "scriptId":"u32"},
    "d0b6cd241f5146acac65b4967288ec1c":{
      "scriptId":"u33"},
    "3af7790d7f1d4481a50c57f864fb4a47":{
      "scriptId":"u34"},
    "181ef29ceee54376af0d1221d8864a8a":{
      "scriptId":"u35"},
    "7a84ef85d973451e985c48a982b83956":{
      "scriptId":"u36"},
    "6d33aa9b952345d18014797f9d2eca95":{
      "scriptId":"u37"},
    "7c985c10415e42e2afa17ceb89712b99":{
      "scriptId":"u38"},
    "9251db969bdd40d4a7a1c3d37f182c23":{
      "scriptId":"u39"},
    "ad75f623163f4f0eb5d1c2816c9eefe4":{
      "scriptId":"u40"},
    "de8fdb83d92f4239849dce67cb5818a2":{
      "scriptId":"u41"},
    "a00c551bacb04ad1ac204468f2c5e964":{
      "scriptId":"u42"},
    "fd46caa0c488407f9dd051d0a4057fa5":{
      "scriptId":"u43"},
    "2a790ea41a0a424bbe00bce110ace6d4":{
      "scriptId":"u44"},
    "738b589d251b430a8232b9f9df9abf59":{
      "scriptId":"u45"},
    "72a6372c78604944bb4faa8db0b8eacc":{
      "scriptId":"u46"},
    "bd090efaf5b44fafa3a3642776e313c3":{
      "scriptId":"u47"},
    "97b7903403864309bd97e9303bd3c17b":{
      "scriptId":"u48"},
    "b35b0f87cf6242bd99277df19dd37218":{
      "scriptId":"u49"},
    "537ef3e93b6b41b9a834481c72162f87":{
      "scriptId":"u50"},
    "3db59b962bd947bbaa42b0bd46a16923":{
      "scriptId":"u51"},
    "011f454c6dcd454d98b5721ae1d47b5d":{
      "scriptId":"u52"},
    "ada378a4c9714b8caf265f57480de03e":{
      "scriptId":"u53"},
    "fdc590800e72410998656915f86908cc":{
      "scriptId":"u54"},
    "23da97126c8149c58d32f9d71f9afff3":{
      "scriptId":"u55"},
    "ea763d184f8c42809c172c738484acbc":{
      "scriptId":"u56"},
    "c2cd169ecafb456992ef50c50a71552a":{
      "scriptId":"u57"},
    "4ede0e5fe6274d3ca5a7b2c9cb1e5d87":{
      "scriptId":"u58"},
    "9590e97cdffa42ec9bf0273566f026c9":{
      "scriptId":"u59"},
    "37dda751c87541e4aa7248cca93f2afb":{
      "scriptId":"u60"},
    "77b9df02f72f4670913f710818232ff1":{
      "scriptId":"u61"},
    "d23e35b2c1cc4aecb294b16ea43d4cd6":{
      "scriptId":"u62"},
    "375742dc8470482199dfb07d1e86fa1c":{
      "scriptId":"u63"},
    "8840ed51bbb0421190c541c9edb73cdc":{
      "scriptId":"u64"},
    "26466de35cb14bc0b14b1277e9275def":{
      "scriptId":"u65"},
    "eb51d4ea07f94de5b5cfc6018e716fd1":{
      "scriptId":"u66"},
    "294ed49fff6548ca91d5510ebd6d55e0":{
      "scriptId":"u67"},
    "ebd98033fe1544dcbc988d5db0dc6f3d":{
      "scriptId":"u68"},
    "5758aa998f53419cbe80bad670537209":{
      "scriptId":"u69"},
    "b620ec508fb348eeb01fb3dc51caba95":{
      "scriptId":"u70"},
    "37aa8f4abb354109b45b50b062ed7bb0":{
      "scriptId":"u71"},
    "150d601d56ca48079b545d9db92d5a44":{
      "scriptId":"u72"},
    "0a34164dddbc46609986d4c4d6fa2fe4":{
      "scriptId":"u73"},
    "b6af1b0b4d1847469dbf3b543f791919":{
      "scriptId":"u74"},
    "381e893b41e040cba18abaa995c2abdc":{
      "scriptId":"u75"},
    "d2a1c4fc8f364428b270cdfb13d8a1ce":{
      "scriptId":"u76"},
    "6cd6a965331c4cf5b5bcab158b8e264c":{
      "scriptId":"u77"},
    "695393fd6def43e98668274350552a2c":{
      "scriptId":"u78"},
    "d0e7b133b44e456292f981a43826e01f":{
      "scriptId":"u79"},
    "92f34dbae2924e489014c6432e35d3fe":{
      "scriptId":"u80"},
    "5905b9ae1d8b461cba69b74cd14b7da7":{
      "scriptId":"u81"},
    "0b40e7168073413492bab75f46d88a6e":{
      "scriptId":"u82"},
    "5419a729924f423ebd6f1d9fe666358f":{
      "scriptId":"u83"},
    "da16c7a386b34bb1be63f4191feaf01d":{
      "scriptId":"u84"},
    "345e5a069f074d1fab996c14ec0d1b48":{
      "scriptId":"u85"},
    "8104f6ae02184c8385ff06cb8ed12993":{
      "scriptId":"u86"},
    "b3a1d7b140ec428084922a0d7e8950f2":{
      "scriptId":"u87"},
    "4414821f0aed454989bb2bb20712f229":{
      "scriptId":"u88"},
    "39c5ae4d707e45ee8414fb1ba03cb73c":{
      "scriptId":"u89"},
    "bad568b775054efe8798c6da69530908":{
      "scriptId":"u90"},
    "97a93b07fd3d402f9994bd2dc100705f":{
      "scriptId":"u91"},
    "c964736e70bb46bfb70644c566e34965":{
      "scriptId":"u92"},
    "4cba0697d42b45a68e11a997f6969814":{
      "scriptId":"u93"},
    "7b46eb6fd4d0449a9ce5430f1d64cb9a":{
      "scriptId":"u94"},
    "ecb63cf44de348f4a2f65b9789855527":{
      "scriptId":"u95"},
    "e7188934807f415b88db3d0b7d648730":{
      "scriptId":"u96"},
    "594dfce3c6b04c34b13708f334ef1896":{
      "scriptId":"u97"},
    "41367c3f686c454991936aff27742e55":{
      "scriptId":"u98"},
    "29dac49bdfd744da84f1ffeb687b601b":{
      "scriptId":"u99"},
    "2eef45ad6db04f6f8a67d606a47eaa0f":{
      "scriptId":"u100"},
    "e9d6cd294b734b57a9a8812a8f3ca051":{
      "scriptId":"u101"},
    "e20c432090cc43eb8221c019f01d2ef3":{
      "scriptId":"u102"},
    "e58b68824b4247339f32578d9d62e9bd":{
      "scriptId":"u103"},
    "b4fc24c49bce4d539db169158c1f5d1c":{
      "scriptId":"u104"}}});