$axure.loadCurrentPage({
  "url":"修改密码.html",
  "generationDate":new Date(1560007707568.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69e98c9bd9e54a3d95798d91bb39aa68",
    "type":"Axure:Page",
    "name":"修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4af3d8371a114f6c89c98e782fe8b0a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":190},
            "size":{
              "width":605,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59486f2b15734b4783006f7f3f4ae121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":190},
                "size":{
                  "width":605,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u0.png"}},
{
          "id":"2b5cf1471f024d488fd64963c22dd017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":317,
              "y":207},
            "size":{
              "width":99,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdcc0960400c47c28bdaa8f28bff375c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":317,
                  "y":207},
                "size":{
                  "width":99,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98d5d96d4dd64a628f4915c4530f9e4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":317,
              "y":273},
            "size":{
              "width":99,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7140c5755c245d0837b549fc5dd51ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":317,
                  "y":273},
                "size":{
                  "width":99,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbafea8b7c914354bc0bd48c911cd34d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":452,
              "y":207},
            "size":{
              "width":247,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"c822de23ba5b4efd836d20ac1b298f14",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":438},
            "size":{
              "width":123,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"other",
                      "description":"修改密码成功！",
                      "description":"修改密码成功！",
                      "popup":{
                        "left":0,
                        "top":0,
                        "width":300,
                        "height":300,
                        "toolbar":false,
                        "scrollbars":true,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":true,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"68f52a23883a451cbdc06d4b21e60751",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":317,
              "y":340},
            "size":{
              "width":123,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d235a09ea8074ed2ba6c7642e5b26325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":317,
                  "y":340},
                "size":{
                  "width":123,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"545690f75fc94c61bebd0834a37f35c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":452,
              "y":273},
            "size":{
              "width":247,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"e3fd649558eb4ffa90cc8f16d7d58993",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":452,
              "y":340},
            "size":{
              "width":247,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"ce5af7864fb34cd1b92fb8e2592a51a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198717c53c3f45f08d63a19aef0ff86e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"9e3531f3a624418b86176ec3e45db7f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba614835557f42bb8317f4b7961a9a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"486c17a2d2d24191ae808f6e29abf0b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c7028a4165a4094885c33b861aa20a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"b75de9a2b5e14d709bb5b5a8ee3a1fab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84265b8f2574f1296da9f832a93eace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"743f39c970e5460ebade5b58630dc309",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a964a341c98e41b1984ffe720b7b7a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c08655d07164b1eb9650c6ed59d4cd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb740e4dfce84b0b89d4a757701db984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f3166b85c6142a598ff8556b6b3143e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aeb41e1d0ae48878119ea0df5f34fdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"858b6818bfde41b1abde455958aee3bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05f5f2871f9546f7b739899fd34faa35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da174a721d4f44edbfeea9cce64f6fbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dafdffadb61a445c9d2dc41c7922b41b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u28.png"}},
{
          "id":"6e57418ed6664b4daa1939a57b7a5292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7060b06a20e94b06942279aecff374ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5a58dc7edc641d889a10517e4041f8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5e8e1adb8b48bb83b363dfed4d3ce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"715fbc522e274f7f97210523b30a3e6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774eb776ce4f41a391e47dd12aa7b8f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4af3d8371a114f6c89c98e782fe8b0a4":{
      "scriptId":"u0"},
    "59486f2b15734b4783006f7f3f4ae121":{
      "scriptId":"u1"},
    "2b5cf1471f024d488fd64963c22dd017":{
      "scriptId":"u2"},
    "cdcc0960400c47c28bdaa8f28bff375c":{
      "scriptId":"u3"},
    "98d5d96d4dd64a628f4915c4530f9e4a":{
      "scriptId":"u4"},
    "e7140c5755c245d0837b549fc5dd51ce":{
      "scriptId":"u5"},
    "dbafea8b7c914354bc0bd48c911cd34d":{
      "scriptId":"u6"},
    "c822de23ba5b4efd836d20ac1b298f14":{
      "scriptId":"u7"},
    "68f52a23883a451cbdc06d4b21e60751":{
      "scriptId":"u8"},
    "d235a09ea8074ed2ba6c7642e5b26325":{
      "scriptId":"u9"},
    "545690f75fc94c61bebd0834a37f35c1":{
      "scriptId":"u10"},
    "e3fd649558eb4ffa90cc8f16d7d58993":{
      "scriptId":"u11"},
    "ce5af7864fb34cd1b92fb8e2592a51a4":{
      "scriptId":"u12"},
    "198717c53c3f45f08d63a19aef0ff86e":{
      "scriptId":"u13"},
    "9e3531f3a624418b86176ec3e45db7f1":{
      "scriptId":"u14"},
    "ba614835557f42bb8317f4b7961a9a52":{
      "scriptId":"u15"},
    "486c17a2d2d24191ae808f6e29abf0b0":{
      "scriptId":"u16"},
    "0c7028a4165a4094885c33b861aa20a7":{
      "scriptId":"u17"},
    "b75de9a2b5e14d709bb5b5a8ee3a1fab":{
      "scriptId":"u18"},
    "c84265b8f2574f1296da9f832a93eace":{
      "scriptId":"u19"},
    "743f39c970e5460ebade5b58630dc309":{
      "scriptId":"u20"},
    "a964a341c98e41b1984ffe720b7b7a97":{
      "scriptId":"u21"},
    "4c08655d07164b1eb9650c6ed59d4cd2":{
      "scriptId":"u22"},
    "eb740e4dfce84b0b89d4a757701db984":{
      "scriptId":"u23"},
    "6f3166b85c6142a598ff8556b6b3143e":{
      "scriptId":"u24"},
    "6aeb41e1d0ae48878119ea0df5f34fdc":{
      "scriptId":"u25"},
    "858b6818bfde41b1abde455958aee3bb":{
      "scriptId":"u26"},
    "05f5f2871f9546f7b739899fd34faa35":{
      "scriptId":"u27"},
    "da174a721d4f44edbfeea9cce64f6fbd":{
      "scriptId":"u28"},
    "dafdffadb61a445c9d2dc41c7922b41b":{
      "scriptId":"u29"},
    "6e57418ed6664b4daa1939a57b7a5292":{
      "scriptId":"u30"},
    "7060b06a20e94b06942279aecff374ec":{
      "scriptId":"u31"},
    "e5a58dc7edc641d889a10517e4041f8b":{
      "scriptId":"u32"},
    "5c5e8e1adb8b48bb83b363dfed4d3ce5":{
      "scriptId":"u33"},
    "715fbc522e274f7f97210523b30a3e6e":{
      "scriptId":"u34"},
    "774eb776ce4f41a391e47dd12aa7b8f3":{
      "scriptId":"u35"}}});