$axure.loadCurrentPage({
  "url":"管理主界面.html",
  "generationDate":new Date(1560007669170.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cfa148891cb94d30be66f45fa0cf091a",
    "type":"Axure:Page",
    "name":"管理主界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"846926d9646f4fb1a83a21a24528782e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":409,
              "y":70},
            "size":{
              "width":241,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9d6bc482824e4989931d2443415ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":409,
                  "y":70},
                "size":{
                  "width":241,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c8f6fcc812a47a19377d37271e70b20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":240},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4df61ccf023a4121b0703843005fe079",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":240},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u2.png"}},
{
          "id":"8bc884b8903f4a9bb31d6c3eef2cd04d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":240},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4939b12e49f145db80be9016cefcab2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":240},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布活动",
                      "target":{
                        "targetType":"page",
                        "url":"发布活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u4.png"}},
{
          "id":"c1e91bd213d44584a662879d64af1ab6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":240},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1c58509e14040d287930b8d6917d397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":240},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u6.png"}},
{
          "id":"97a33b5098e546f0b88bb96e97744429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":240},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df2eb014d67a450abe1cd76e3654054d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":240},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u8.png"}},
{
          "id":"5193170913d24d6da5a6bbaa04f1d5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":179,
              "y":365},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3869f300e4742018a35178539c8589e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":179,
                  "y":365},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f050fa1429914ef7807554be8b44e2eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":349,
              "y":365},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f1659f3d8840c9b63bd1e360ca226b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":349,
                  "y":365},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbe507b29d834ed595b615f78aa5735c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":689,
              "y":365},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fc3a332066e435cbe0dad1a2a406ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":689,
                  "y":365},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15e69cb6ca354d4e822ced5d4ae75719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":529,
              "y":365},
            "size":{
              "width":82,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d58220a8b2e41b2888e49ba1c4a86c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":529,
                  "y":365},
                "size":{
                  "width":82,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4215dc49784439087b443c0cdc70305",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":240},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a8448d071854200ae3fb400c17dabad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":240},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u18.png"}},
{
          "id":"e9471e896dac47c4a8478987335f33e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":840,
              "y":365},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41e38e15d6664076a1abfd5c5327c0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":840,
                  "y":365},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "846926d9646f4fb1a83a21a24528782e":{
      "scriptId":"u0"},
    "6b9d6bc482824e4989931d2443415ab2":{
      "scriptId":"u1"},
    "1c8f6fcc812a47a19377d37271e70b20":{
      "scriptId":"u2"},
    "4df61ccf023a4121b0703843005fe079":{
      "scriptId":"u3"},
    "8bc884b8903f4a9bb31d6c3eef2cd04d":{
      "scriptId":"u4"},
    "4939b12e49f145db80be9016cefcab2e":{
      "scriptId":"u5"},
    "c1e91bd213d44584a662879d64af1ab6":{
      "scriptId":"u6"},
    "a1c58509e14040d287930b8d6917d397":{
      "scriptId":"u7"},
    "97a33b5098e546f0b88bb96e97744429":{
      "scriptId":"u8"},
    "df2eb014d67a450abe1cd76e3654054d":{
      "scriptId":"u9"},
    "5193170913d24d6da5a6bbaa04f1d5c1":{
      "scriptId":"u10"},
    "b3869f300e4742018a35178539c8589e":{
      "scriptId":"u11"},
    "f050fa1429914ef7807554be8b44e2eb":{
      "scriptId":"u12"},
    "89f1659f3d8840c9b63bd1e360ca226b":{
      "scriptId":"u13"},
    "dbe507b29d834ed595b615f78aa5735c":{
      "scriptId":"u14"},
    "2fc3a332066e435cbe0dad1a2a406ef6":{
      "scriptId":"u15"},
    "15e69cb6ca354d4e822ced5d4ae75719":{
      "scriptId":"u16"},
    "3d58220a8b2e41b2888e49ba1c4a86c7":{
      "scriptId":"u17"},
    "c4215dc49784439087b443c0cdc70305":{
      "scriptId":"u18"},
    "4a8448d071854200ae3fb400c17dabad":{
      "scriptId":"u19"},
    "e9471e896dac47c4a8478987335f33e9":{
      "scriptId":"u20"},
    "41e38e15d6664076a1abfd5c5327c0bc":{
      "scriptId":"u21"}}});