$axure.loadCurrentPage({
  "url":"最新活动.html",
  "generationDate":new Date(1560007707829.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bb5c4c37ed34cbb92aecc861595e301",
    "type":"Axure:Page",
    "name":"最新活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5441232cc7ff4741a833235345f9569d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":180},
            "size":{
              "width":584,
              "height":290},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e3769a071d464f84b67ed44e467502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":180},
                "size":{
                  "width":584,
                  "height":290},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/最新活动/u0.png"}},
{
          "id":"88bbc4a821384f7ea03e5a98a7e2c42b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce51b8c84b394b5d9ac5e8b3caea2ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"572f6babcc9b411b8d2e36058bb0f96d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0296b08695d4c6f8588b09fcda79f73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"9cc0c8a172924589a3951ef0bb3aa03b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddc349a35a5b4ae990a60fb2ababf589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"dd477709fdae4643b728050650eb3e74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581e14113af2433b890f69bb3543b76d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"ec77bdc917e44df1b4326c95cd7a1114",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77f1db87441746a3943c00ba4e53ab88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62205b4e994847dd8c659248d1866a54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"624728eb01964038988c5fb24f4063c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9323ecdafa5d4ccf8ecfbc8a9d842c40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"786aa25b88c446e79bf461a51fe0a862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf24f032bb094f6eb624141eacf7c85a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6116fc3b0e7c41128d8d8b106af75aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a64bac6fc87e49beae088193cde1aa7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3578790aee25450cafc3ff95e1efe9c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u28.png"}},
{
          "id":"b0c2ba249f7144caafb4fb75b861782e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f60d57c315e14581827d6f842ccb381e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ce2f3b4569347ebb1d35833f3f00eb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cccc7a01790449e1971ca83b1128cdf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"3f7beee5765e4b29b607d1a080ee7f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41637a65f5844e6a48afcde14553b11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5441232cc7ff4741a833235345f9569d":{
      "scriptId":"u0"},
    "36e3769a071d464f84b67ed44e467502":{
      "scriptId":"u1"},
    "88bbc4a821384f7ea03e5a98a7e2c42b":{
      "scriptId":"u2"},
    "ce51b8c84b394b5d9ac5e8b3caea2ef4":{
      "scriptId":"u3"},
    "572f6babcc9b411b8d2e36058bb0f96d":{
      "scriptId":"u4"},
    "e0296b08695d4c6f8588b09fcda79f73":{
      "scriptId":"u5"},
    "9cc0c8a172924589a3951ef0bb3aa03b":{
      "scriptId":"u6"},
    "ddc349a35a5b4ae990a60fb2ababf589":{
      "scriptId":"u7"},
    "dd477709fdae4643b728050650eb3e74":{
      "scriptId":"u8"},
    "581e14113af2433b890f69bb3543b76d":{
      "scriptId":"u9"},
    "ec77bdc917e44df1b4326c95cd7a1114":{
      "scriptId":"u10"},
    "77f1db87441746a3943c00ba4e53ab88":{
      "scriptId":"u11"},
    "62205b4e994847dd8c659248d1866a54":{
      "scriptId":"u12"},
    "624728eb01964038988c5fb24f4063c6":{
      "scriptId":"u13"},
    "9323ecdafa5d4ccf8ecfbc8a9d842c40":{
      "scriptId":"u14"},
    "786aa25b88c446e79bf461a51fe0a862":{
      "scriptId":"u15"},
    "bf24f032bb094f6eb624141eacf7c85a":{
      "scriptId":"u16"},
    "6116fc3b0e7c41128d8d8b106af75aa5":{
      "scriptId":"u17"},
    "a64bac6fc87e49beae088193cde1aa7a":{
      "scriptId":"u18"},
    "3578790aee25450cafc3ff95e1efe9c6":{
      "scriptId":"u19"},
    "b0c2ba249f7144caafb4fb75b861782e":{
      "scriptId":"u20"},
    "f60d57c315e14581827d6f842ccb381e":{
      "scriptId":"u21"},
    "2ce2f3b4569347ebb1d35833f3f00eb4":{
      "scriptId":"u22"},
    "cccc7a01790449e1971ca83b1128cdf0":{
      "scriptId":"u23"},
    "3f7beee5765e4b29b607d1a080ee7f1c":{
      "scriptId":"u24"},
    "d41637a65f5844e6a48afcde14553b11":{
      "scriptId":"u25"}}});