$axure.loadCurrentPage({
  "url":"注册用户.html",
  "generationDate":new Date(1560007669326.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"40fe1af0525343d1bf89866f30626477",
    "type":"Axure:Page",
    "name":"注册用户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8db9b93ab62b4e7088552e147d6206a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":190},
            "size":{
              "width":615,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01b62e8e72b4cc2bac31c4838e77634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":190},
                "size":{
                  "width":615,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u0.png"}},
{
          "id":"34ddb5cbd2fa4b2bbcd6517e3720e66a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":313,
              "y":226},
            "size":{
              "width":126,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c40ed02b7e34f43b22869ac5284a899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":313,
                  "y":226},
                "size":{
                  "width":126,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b31bc592df164dda92342b139aadd04d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":439,
              "y":223},
            "size":{
              "width":292,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4f180b6ec4c147c7800dae1ef4afaee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":314,
              "y":280},
            "size":{
              "width":126,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"897c94139f0942f69e413cbb50672247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":314,
                  "y":280},
                "size":{
                  "width":126,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeedd5ccd3ec4e5680480d81296cb0aa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":440,
              "y":277},
            "size":{
              "width":292,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"42df6cf366af4f6ca79b8f524e0b5503",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":313,
              "y":331},
            "size":{
              "width":126,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c998d14baf52476aaa96395434d7b456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":313,
                  "y":331},
                "size":{
                  "width":126,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1da6f02c17b47449f4dd2d6779f0138",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":439,
              "y":328},
            "size":{
              "width":151,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"b403f3b2fca04e8994600f1bf18abc02",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":328},
            "size":{
              "width":100,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"other",
                      "description":"验证码已发送",
                      "description":"验证码已发送",
                      "popup":{
                        "left":0,
                        "top":0,
                        "width":300,
                        "height":300,
                        "toolbar":false,
                        "scrollbars":true,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":true,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"ba9a6a7a3d7e4fa68be9a2470d66b7a0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":386},
            "size":{
              "width":100,
              "height":54}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"other",
                      "description":"用户注册成功！<br>默认密码为：123456",
                      "description":"用户注册成功！<br>默认密码为：123456",
                      "popup":{
                        "left":0,
                        "top":0,
                        "width":300,
                        "height":300,
                        "toolbar":false,
                        "scrollbars":true,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":true,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"521b2387320e4b2087245c809b3c6a7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9992c3959bf4db0b1d6430bd356a544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u2.png"}},
{
          "id":"8e916fa99e2348a286c8e2ec4c475161",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655cc24798f3458a83c8d0e1f05e836f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布活动",
                      "target":{
                        "targetType":"page",
                        "url":"发布活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u4.png"}},
{
          "id":"0e18ac08dca24d89a83b7c46b9d331a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b13c8f1d6b46f9b6208439fc4a5162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u6.png"}},
{
          "id":"02eecdf69efc478bab8b7a0201db1306",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d14420dd6a2c42d680ba5bc54afca02b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u8.png"}},
{
          "id":"3da76185f12548cfa8fc8803ce95a896",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f8d5abebd8426da5dd6275e20f1dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff050c57bd874e629fb81a88a8f8df61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4476f586bb4094a991d8bd55405bda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da735df9d201456c97d50ca3a56977b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb330cc08564d449ba92e8b0a30cf73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a52fe12c1484021b6d7ad9988c6755a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b80cec5ef824793ade99f303bb9c46b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c51b691b11364ed2a6167d6948d3730b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a47f615f39d46e894bd55e80474e2d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理主界面",
                      "target":{
                        "targetType":"page",
                        "url":"管理主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u25.png"}},
{
          "id":"56e72562e4ed4ef087d0f4359e676da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e6729089ea74633988306923621bc8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb5ab7bac46542dabc7fd43d76585c69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c3aa494d8641c2887ee5556781a9b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u18.png"}},
{
          "id":"d717b76ee4904db7b3af1261953926f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb62177f4c054898b6db13f0cfed42b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8db9b93ab62b4e7088552e147d6206a7":{
      "scriptId":"u0"},
    "e01b62e8e72b4cc2bac31c4838e77634":{
      "scriptId":"u1"},
    "34ddb5cbd2fa4b2bbcd6517e3720e66a":{
      "scriptId":"u2"},
    "9c40ed02b7e34f43b22869ac5284a899":{
      "scriptId":"u3"},
    "b31bc592df164dda92342b139aadd04d":{
      "scriptId":"u4"},
    "4f180b6ec4c147c7800dae1ef4afaee2":{
      "scriptId":"u5"},
    "897c94139f0942f69e413cbb50672247":{
      "scriptId":"u6"},
    "eeedd5ccd3ec4e5680480d81296cb0aa":{
      "scriptId":"u7"},
    "42df6cf366af4f6ca79b8f524e0b5503":{
      "scriptId":"u8"},
    "c998d14baf52476aaa96395434d7b456":{
      "scriptId":"u9"},
    "c1da6f02c17b47449f4dd2d6779f0138":{
      "scriptId":"u10"},
    "b403f3b2fca04e8994600f1bf18abc02":{
      "scriptId":"u11"},
    "ba9a6a7a3d7e4fa68be9a2470d66b7a0":{
      "scriptId":"u12"},
    "521b2387320e4b2087245c809b3c6a7c":{
      "scriptId":"u13"},
    "d9992c3959bf4db0b1d6430bd356a544":{
      "scriptId":"u14"},
    "8e916fa99e2348a286c8e2ec4c475161":{
      "scriptId":"u15"},
    "655cc24798f3458a83c8d0e1f05e836f":{
      "scriptId":"u16"},
    "0e18ac08dca24d89a83b7c46b9d331a6":{
      "scriptId":"u17"},
    "58b13c8f1d6b46f9b6208439fc4a5162":{
      "scriptId":"u18"},
    "02eecdf69efc478bab8b7a0201db1306":{
      "scriptId":"u19"},
    "d14420dd6a2c42d680ba5bc54afca02b":{
      "scriptId":"u20"},
    "3da76185f12548cfa8fc8803ce95a896":{
      "scriptId":"u21"},
    "a6f8d5abebd8426da5dd6275e20f1dea":{
      "scriptId":"u22"},
    "ff050c57bd874e629fb81a88a8f8df61":{
      "scriptId":"u23"},
    "cc4476f586bb4094a991d8bd55405bda":{
      "scriptId":"u24"},
    "da735df9d201456c97d50ca3a56977b9":{
      "scriptId":"u25"},
    "8eb330cc08564d449ba92e8b0a30cf73":{
      "scriptId":"u26"},
    "9a52fe12c1484021b6d7ad9988c6755a":{
      "scriptId":"u27"},
    "7b80cec5ef824793ade99f303bb9c46b":{
      "scriptId":"u28"},
    "c51b691b11364ed2a6167d6948d3730b":{
      "scriptId":"u29"},
    "7a47f615f39d46e894bd55e80474e2d9":{
      "scriptId":"u30"},
    "56e72562e4ed4ef087d0f4359e676da3":{
      "scriptId":"u31"},
    "2e6729089ea74633988306923621bc8d":{
      "scriptId":"u32"},
    "fb5ab7bac46542dabc7fd43d76585c69":{
      "scriptId":"u33"},
    "85c3aa494d8641c2887ee5556781a9b9":{
      "scriptId":"u34"},
    "d717b76ee4904db7b3af1261953926f1":{
      "scriptId":"u35"},
    "bb62177f4c054898b6db13f0cfed42b8":{
      "scriptId":"u36"}}});