$axure.loadCurrentPage({
  "url":"用户界面.html",
  "generationDate":new Date(1560007707517.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cfa148891cb94d30be66f45fa0cf091a",
    "type":"Axure:Page",
    "name":"用户界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a86f15b305854885aa212030d6030fd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":250},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813a507cbe06411a8127e723f7483080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"2cd3cadb368a4785ad6d7bcf9483ceea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":664,
              "y":250},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd06fdc7133f48148e12901b12c51136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":664,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"5abbdab93a0b478199ce756cdf0645e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":250},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a535e4c32b9428288a78075d69860cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"32c84d3fcee242518133de3bcd3cc0a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":250},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fcdff8ffbce43e292d1d08b40f6dbc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"846926d9646f4fb1a83a21a24528782e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":351,
              "y":65},
            "size":{
              "width":241,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b9d6bc482824e4989931d2443415ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":351,
                  "y":65},
                "size":{
                  "width":241,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e521dd846a6447f290b4b32232fdb05d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":74,
              "y":375},
            "size":{
              "width":80,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b101340c82457aa0ed40079861eb41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":74,
                  "y":375},
                "size":{
                  "width":80,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aa3a22adef44254b851688eca73d195",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":274,
              "y":375},
            "size":{
              "width":80,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d65f41451909418bb524c7a467390f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":274,
                  "y":375},
                "size":{
                  "width":80,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cabf23f68c64ebe87285c865e474db8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":674,
              "y":375},
            "size":{
              "width":80,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a30f59521ea445b19682e20ff033608e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":674,
                  "y":375},
                "size":{
                  "width":80,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"045c85f92016435b954a8ec52d92be78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":474,
              "y":375},
            "size":{
              "width":80,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c044c841afec43628acc3c4f935868fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":474,
                  "y":375},
                "size":{
                  "width":80,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbf4c921f0214c2481debbef1992dda6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":80},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6334b73d2f042c6bedc025ac08128d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":80},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 挂机锁定",
                      "target":{
                        "targetType":"page",
                        "url":"挂机锁定.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u18.png"}},
{
          "id":"ea3dc80dc367431eb452c70660d1bd6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":80},
            "size":{
              "width":35,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abca8259cc9c4336904ca95b2581ad48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":815,
                  "y":80},
                "size":{
                  "width":35,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u20.png"}},
{
          "id":"3200dc66d83e469f953d8b37c34a0662",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":738,
              "y":125},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2beb0ecc28a241e481674e36d689a7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":738,
                  "y":125},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2680061de4f848c1adace18b1738032c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":802,
              "y":125},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f71ee970ffb43109aaa7a7bc37d6a64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":802,
                  "y":125},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80a16a516fe4ebfb252aa48a5618242",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":250},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"599a1184dfe4424fa43cab9d7d024b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"8849ddc6f471489a871015e320b69643",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":860,
              "y":375},
            "size":{
              "width":60,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"689fb8363fe0468a983375801f66aa89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":860,
                  "y":375},
                "size":{
                  "width":60,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3f334a60c4b43a7bd2b6e4f1fd5d309",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":140},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45352b1019d5467e92460850562b7176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":140},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fdd82f1e98e43948429c1763873a691",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":171},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea047d5c39b4dd9897846589fd8e60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":171},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bc1411f736140aebd651733adcbb4a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":200},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48f282fe61b840698d92e15ab746a952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":200},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce4f4a2709fb4a0dbb6b95b1b3650c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":240,
              "y":140},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a220301d3b8f476a93696aa0d412a9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":240,
                  "y":140},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f74129c2aa15493491e0351c84b826ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":240,
              "y":171},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9578208b7b6f40b996722bec372fa950",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":240,
                  "y":171},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4d1f5da36f3431a9c7a1880ab56b6a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":240,
              "y":200},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d23b377c2e4dc29ca702f7b96c4719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":240,
                  "y":200},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a86f15b305854885aa212030d6030fd9":{
      "scriptId":"u0"},
    "813a507cbe06411a8127e723f7483080":{
      "scriptId":"u1"},
    "2cd3cadb368a4785ad6d7bcf9483ceea":{
      "scriptId":"u2"},
    "bd06fdc7133f48148e12901b12c51136":{
      "scriptId":"u3"},
    "5abbdab93a0b478199ce756cdf0645e6":{
      "scriptId":"u4"},
    "9a535e4c32b9428288a78075d69860cb":{
      "scriptId":"u5"},
    "32c84d3fcee242518133de3bcd3cc0a6":{
      "scriptId":"u6"},
    "0fcdff8ffbce43e292d1d08b40f6dbc2":{
      "scriptId":"u7"},
    "846926d9646f4fb1a83a21a24528782e":{
      "scriptId":"u8"},
    "6b9d6bc482824e4989931d2443415ab2":{
      "scriptId":"u9"},
    "e521dd846a6447f290b4b32232fdb05d":{
      "scriptId":"u10"},
    "b8b101340c82457aa0ed40079861eb41":{
      "scriptId":"u11"},
    "8aa3a22adef44254b851688eca73d195":{
      "scriptId":"u12"},
    "d65f41451909418bb524c7a467390f6a":{
      "scriptId":"u13"},
    "8cabf23f68c64ebe87285c865e474db8":{
      "scriptId":"u14"},
    "a30f59521ea445b19682e20ff033608e":{
      "scriptId":"u15"},
    "045c85f92016435b954a8ec52d92be78":{
      "scriptId":"u16"},
    "c044c841afec43628acc3c4f935868fb":{
      "scriptId":"u17"},
    "fbf4c921f0214c2481debbef1992dda6":{
      "scriptId":"u18"},
    "c6334b73d2f042c6bedc025ac08128d4":{
      "scriptId":"u19"},
    "ea3dc80dc367431eb452c70660d1bd6e":{
      "scriptId":"u20"},
    "abca8259cc9c4336904ca95b2581ad48":{
      "scriptId":"u21"},
    "3200dc66d83e469f953d8b37c34a0662":{
      "scriptId":"u22"},
    "2beb0ecc28a241e481674e36d689a7f9":{
      "scriptId":"u23"},
    "2680061de4f848c1adace18b1738032c":{
      "scriptId":"u24"},
    "9f71ee970ffb43109aaa7a7bc37d6a64":{
      "scriptId":"u25"},
    "f80a16a516fe4ebfb252aa48a5618242":{
      "scriptId":"u26"},
    "599a1184dfe4424fa43cab9d7d024b46":{
      "scriptId":"u27"},
    "8849ddc6f471489a871015e320b69643":{
      "scriptId":"u28"},
    "689fb8363fe0468a983375801f66aa89":{
      "scriptId":"u29"},
    "a3f334a60c4b43a7bd2b6e4f1fd5d309":{
      "scriptId":"u30"},
    "45352b1019d5467e92460850562b7176":{
      "scriptId":"u31"},
    "6fdd82f1e98e43948429c1763873a691":{
      "scriptId":"u32"},
    "1ea047d5c39b4dd9897846589fd8e60e":{
      "scriptId":"u33"},
    "7bc1411f736140aebd651733adcbb4a9":{
      "scriptId":"u34"},
    "48f282fe61b840698d92e15ab746a952":{
      "scriptId":"u35"},
    "ce4f4a2709fb4a0dbb6b95b1b3650c8e":{
      "scriptId":"u36"},
    "a220301d3b8f476a93696aa0d412a9d2":{
      "scriptId":"u37"},
    "f74129c2aa15493491e0351c84b826ec":{
      "scriptId":"u38"},
    "9578208b7b6f40b996722bec372fa950":{
      "scriptId":"u39"},
    "d4d1f5da36f3431a9c7a1880ab56b6a6":{
      "scriptId":"u40"},
    "b5d23b377c2e4dc29ca702f7b96c4719":{
      "scriptId":"u41"}}});