$axure.loadCurrentPage({
  "url":"订餐.html",
  "generationDate":new Date(1560007708020.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7613d97c2ad24f0f8b69dc2e8d556697",
    "type":"Axure:Page",
    "name":"订餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"22815ac2503f49d49393d5608bb3d969",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":176},
            "size":{
              "width":599,
              "height":413}},
          "adaptiveStyles":{
}},
{
          "id":"378abab4125047a9912612e7bcd70c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":210},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7906b8afb24486bbcc21b8a0723b98c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":210},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u1.jpg"}},
{
          "id":"b7de87068777451abf40b227f4850cfe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":452},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b36681724534d94988727109226d6b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":452},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u3.jpg"}},
{
          "id":"a11a45be14ae4d039e3826e00d612e59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":452},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd874392eeed4043b9cd798849ab25d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":452},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u5.jpg"}},
{
          "id":"ded0ad7fbb0a4c9cafa66863a9807a23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":452},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ec4504708e4ad48c1afd3e7dade59d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":452},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u7.jpg"}},
{
          "id":"9d12f04b237046f2b1132c370362ada6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":334},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"459c5dac56ec405490937751b570c979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":334},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u9.jpg"}},
{
          "id":"6467be07c9c24290a5f5380cbf63c998",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":334},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3955c2fb9d14c838251a127b2bae71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":334},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u11.jpg"}},
{
          "id":"732593320f2142de99cef13eeffdc95b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":334},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd87b4cb7bc949d7b080deb26d52ace7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":334},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u13.jpeg"}},
{
          "id":"ef1728beb58045ca8cecb7f5e88ce45c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":210},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"161553716624450a9430217350d26b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":210},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u15.jpg"}},
{
          "id":"89a06f6bb42c47d992fcdc6c45a9e4db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":210},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"323c97cf7f4441eaa7a4c403fc420156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":210},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u17.jpg"}},
{
          "id":"b0c4e3e4d7f5457c8a6bfed536f128b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":295},
            "size":{
              "width":46,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5945211a2e9496fbafcb19708a2fbc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":295},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f73f5b049aac45a9a406ae6b2ef3e6bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":294},
            "size":{
              "width":46,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8794816d36e94cca97d7d9ffc9f44b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":407,
                  "y":294},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecda7c5f89284d8ea6548c26e33aae01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":577,
              "y":295},
            "size":{
              "width":46,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1897b6f1da4b4136a9b1d5a71b555071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":577,
                  "y":295},
                "size":{
                  "width":46,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07e415e50a4c4a6a99cca535c1a32ec5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":412},
            "size":{
              "width":73,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79558f6171ca4138a04ce1f1227a6b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":412},
                "size":{
                  "width":73,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61631717ab304f79923d7abfd9c739f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":419},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e201641eafc849b7929a642513ad23f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":395,
                  "y":419},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"732f895a65d247caac40abca336532a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":412},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63d70dee87d4fdd9951974a3a92e368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":412},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"711c4da107d74f0bb72fb315d263b4b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":537},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e32cbc0a4b40a9a9f563c3f0792078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":537},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8660ed0840ab413999e80a130a8ef67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":537},
            "size":{
              "width":55,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a5cb05dab741c995c0c0756dec519d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":537},
                "size":{
                  "width":55,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c0b27caff234e3ca69b236cf6f883ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":537},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3ccdd408fc741d2b4cd4eeb35a11f46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":537},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01356c259e924fc3b94b63ca9d54e119",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":176},
            "size":{
              "width":200,
              "height":349}},
          "adaptiveStyles":{
}},
{
          "id":"d5d8c09872c84593a2e480b94265534a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":564},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}},
{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 支付二维码",
                      "target":{
                        "targetType":"page",
                        "url":"支付二维码.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"01744a067f5a4c95b55cf481cc08b681",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":545},
            "size":{
              "width":90,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f268aae3d5ba4a74ba3857e2593e9edd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":545},
                "size":{
                  "width":90,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"054594d04120463f8a28d3648662e82a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":191},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"881d3c6678a54417a1d4ccf733d4de11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":191},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u15.jpg"}},
{
          "id":"45e1c8b567094fcfb7b2a6eadaae1be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":276},
            "size":{
              "width":88,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a402f4fe78284376abff52f12ecfe36c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":276},
                "size":{
                  "width":88,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8bd92ffd92d451dad926f469fd38435",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":306},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c136388d557c4517ac13d27ab983efd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":306},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u11.jpg"}},
{
          "id":"46b0f8d2b17c4009a259e0c4bc6926c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":391},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c3b05d8ecc4457b28a729a29d141d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":391},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cc4bba92c874162b8de2b9fbf3700ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":227},
            "size":{
              "width":84,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36987953a1cf4994932e690742a9d0c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":227},
                "size":{
                  "width":84,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u49.png"}},
{
          "id":"0aa6843d599b4fbcb545c1793406f9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":342},
            "size":{
              "width":84,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"010c906bc796480fb2bb277919c77d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":342},
                "size":{
                  "width":84,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u49.png"}},
{
          "id":"f19ea79dd66846ecae33391984866bad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e7bd948f634ff185e02c60a6f4afa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":377,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u0.png"}},
{
          "id":"32a6aadf1d244d98ac338d9d8b7c333c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2853aea2634a472799363f91b1f20d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 最新活动",
                      "target":{
                        "targetType":"page",
                        "url":"最新活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u2.png"}},
{
          "id":"b7b0e68c026d43568b394c6a00f3fa62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3252a23d5028468c89ca4c7b07a3b856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u4.png"}},
{
          "id":"4eaa69440bf249d08596684a228c47b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22edff913b1346c3b3eb08870cd2669d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史信息",
                      "target":{
                        "targetType":"page",
                        "url":"历史信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u6.png"}},
{
          "id":"2c88b7f739b74f32a1ef0887e0806f2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":362,
              "y":144},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9986f1b3bcdf4b8e845b4d7c6c74baa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":362,
                  "y":144},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47630e6a7d06432098ed37fd65151ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":482,
              "y":144},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eb952c644b9496d98df6ee10d9e0e49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":482,
                  "y":144},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11482768a1d1403ab97da691fa6b97d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":702,
              "y":144},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ad3595822047e1b36ef11bfd3deba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":702,
                  "y":144},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9deb128213754075a19c6d6312b42cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":592,
              "y":144},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e2d3c7a0264a9c80d540789c4968e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":592,
                  "y":144},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56ac38d02c8a488c932f6ad70d398fa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401caead00964bc3b1c4e0d2224710f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户界面",
                      "target":{
                        "targetType":"page",
                        "url":"用户界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改密码/u28.png"}},
{
          "id":"1367c1652ee14547abdf3bb19f2f10a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":260,
              "y":146},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00bdc6817c3f4f84aa06233930dd4c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":260,
                  "y":146},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf554a4930c44bcb8be609943b723c98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":79},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16a16f9fa8c340fc8dbbc799a1e6c93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":79},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户界面/u26.png"}},
{
          "id":"0bb6197a1f034a07b9ad9b23badd3623",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":820,
              "y":147},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee6bed37669408688b4290e12a5bd1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":820,
                  "y":147},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "22815ac2503f49d49393d5608bb3d969":{
      "scriptId":"u0"},
    "378abab4125047a9912612e7bcd70c5e":{
      "scriptId":"u1"},
    "e7906b8afb24486bbcc21b8a0723b98c":{
      "scriptId":"u2"},
    "b7de87068777451abf40b227f4850cfe":{
      "scriptId":"u3"},
    "8b36681724534d94988727109226d6b0":{
      "scriptId":"u4"},
    "a11a45be14ae4d039e3826e00d612e59":{
      "scriptId":"u5"},
    "cd874392eeed4043b9cd798849ab25d9":{
      "scriptId":"u6"},
    "ded0ad7fbb0a4c9cafa66863a9807a23":{
      "scriptId":"u7"},
    "00ec4504708e4ad48c1afd3e7dade59d":{
      "scriptId":"u8"},
    "9d12f04b237046f2b1132c370362ada6":{
      "scriptId":"u9"},
    "459c5dac56ec405490937751b570c979":{
      "scriptId":"u10"},
    "6467be07c9c24290a5f5380cbf63c998":{
      "scriptId":"u11"},
    "b3955c2fb9d14c838251a127b2bae71a":{
      "scriptId":"u12"},
    "732593320f2142de99cef13eeffdc95b":{
      "scriptId":"u13"},
    "fd87b4cb7bc949d7b080deb26d52ace7":{
      "scriptId":"u14"},
    "ef1728beb58045ca8cecb7f5e88ce45c":{
      "scriptId":"u15"},
    "161553716624450a9430217350d26b14":{
      "scriptId":"u16"},
    "89a06f6bb42c47d992fcdc6c45a9e4db":{
      "scriptId":"u17"},
    "323c97cf7f4441eaa7a4c403fc420156":{
      "scriptId":"u18"},
    "b0c4e3e4d7f5457c8a6bfed536f128b5":{
      "scriptId":"u19"},
    "f5945211a2e9496fbafcb19708a2fbc8":{
      "scriptId":"u20"},
    "f73f5b049aac45a9a406ae6b2ef3e6bc":{
      "scriptId":"u21"},
    "8794816d36e94cca97d7d9ffc9f44b98":{
      "scriptId":"u22"},
    "ecda7c5f89284d8ea6548c26e33aae01":{
      "scriptId":"u23"},
    "1897b6f1da4b4136a9b1d5a71b555071":{
      "scriptId":"u24"},
    "07e415e50a4c4a6a99cca535c1a32ec5":{
      "scriptId":"u25"},
    "79558f6171ca4138a04ce1f1227a6b9e":{
      "scriptId":"u26"},
    "61631717ab304f79923d7abfd9c739f5":{
      "scriptId":"u27"},
    "e201641eafc849b7929a642513ad23f8":{
      "scriptId":"u28"},
    "732f895a65d247caac40abca336532a1":{
      "scriptId":"u29"},
    "e63d70dee87d4fdd9951974a3a92e368":{
      "scriptId":"u30"},
    "711c4da107d74f0bb72fb315d263b4b5":{
      "scriptId":"u31"},
    "a0e32cbc0a4b40a9a9f563c3f0792078":{
      "scriptId":"u32"},
    "8660ed0840ab413999e80a130a8ef67b":{
      "scriptId":"u33"},
    "80a5cb05dab741c995c0c0756dec519d":{
      "scriptId":"u34"},
    "5c0b27caff234e3ca69b236cf6f883ca":{
      "scriptId":"u35"},
    "e3ccdd408fc741d2b4cd4eeb35a11f46":{
      "scriptId":"u36"},
    "01356c259e924fc3b94b63ca9d54e119":{
      "scriptId":"u37"},
    "d5d8c09872c84593a2e480b94265534a":{
      "scriptId":"u38"},
    "01744a067f5a4c95b55cf481cc08b681":{
      "scriptId":"u39"},
    "f268aae3d5ba4a74ba3857e2593e9edd":{
      "scriptId":"u40"},
    "054594d04120463f8a28d3648662e82a":{
      "scriptId":"u41"},
    "881d3c6678a54417a1d4ccf733d4de11":{
      "scriptId":"u42"},
    "45e1c8b567094fcfb7b2a6eadaae1be8":{
      "scriptId":"u43"},
    "a402f4fe78284376abff52f12ecfe36c":{
      "scriptId":"u44"},
    "f8bd92ffd92d451dad926f469fd38435":{
      "scriptId":"u45"},
    "c136388d557c4517ac13d27ab983efd2":{
      "scriptId":"u46"},
    "46b0f8d2b17c4009a259e0c4bc6926c3":{
      "scriptId":"u47"},
    "46c3b05d8ecc4457b28a729a29d141d3":{
      "scriptId":"u48"},
    "4cc4bba92c874162b8de2b9fbf3700ff":{
      "scriptId":"u49"},
    "36987953a1cf4994932e690742a9d0c4":{
      "scriptId":"u50"},
    "0aa6843d599b4fbcb545c1793406f9b3":{
      "scriptId":"u51"},
    "010c906bc796480fb2bb277919c77d8d":{
      "scriptId":"u52"},
    "f19ea79dd66846ecae33391984866bad":{
      "scriptId":"u53"},
    "43e7bd948f634ff185e02c60a6f4afa9":{
      "scriptId":"u54"},
    "32a6aadf1d244d98ac338d9d8b7c333c":{
      "scriptId":"u55"},
    "2853aea2634a472799363f91b1f20d74":{
      "scriptId":"u56"},
    "b7b0e68c026d43568b394c6a00f3fa62":{
      "scriptId":"u57"},
    "3252a23d5028468c89ca4c7b07a3b856":{
      "scriptId":"u58"},
    "4eaa69440bf249d08596684a228c47b6":{
      "scriptId":"u59"},
    "22edff913b1346c3b3eb08870cd2669d":{
      "scriptId":"u60"},
    "2c88b7f739b74f32a1ef0887e0806f2c":{
      "scriptId":"u61"},
    "9986f1b3bcdf4b8e845b4d7c6c74baa4":{
      "scriptId":"u62"},
    "47630e6a7d06432098ed37fd65151ba3":{
      "scriptId":"u63"},
    "6eb952c644b9496d98df6ee10d9e0e49":{
      "scriptId":"u64"},
    "11482768a1d1403ab97da691fa6b97d0":{
      "scriptId":"u65"},
    "e8ad3595822047e1b36ef11bfd3deba2":{
      "scriptId":"u66"},
    "9deb128213754075a19c6d6312b42cc8":{
      "scriptId":"u67"},
    "59e2d3c7a0264a9c80d540789c4968e8":{
      "scriptId":"u68"},
    "56ac38d02c8a488c932f6ad70d398fa6":{
      "scriptId":"u69"},
    "401caead00964bc3b1c4e0d2224710f4":{
      "scriptId":"u70"},
    "1367c1652ee14547abdf3bb19f2f10a6":{
      "scriptId":"u71"},
    "00bdc6817c3f4f84aa06233930dd4c14":{
      "scriptId":"u72"},
    "cf554a4930c44bcb8be609943b723c98":{
      "scriptId":"u73"},
    "16a16f9fa8c340fc8dbbc799a1e6c93a":{
      "scriptId":"u74"},
    "0bb6197a1f034a07b9ad9b23badd3623":{
      "scriptId":"u75"},
    "6ee6bed37669408688b4290e12a5bd1c":{
      "scriptId":"u76"}}});