$axure.loadCurrentPage({
  "url":"改密.html",
  "generationDate":new Date(1560007669390.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69e98c9bd9e54a3d95798d91bb39aa68",
    "type":"Axure:Page",
    "name":"改密",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4af3d8371a114f6c89c98e782fe8b0a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":190},
            "size":{
              "width":605,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59486f2b15734b4783006f7f3f4ae121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":190},
                "size":{
                  "width":605,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/改密/u0.png"}},
{
          "id":"98d5d96d4dd64a628f4915c4530f9e4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":317,
              "y":273},
            "size":{
              "width":99,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7140c5755c245d0837b549fc5dd51ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":317,
                  "y":273},
                "size":{
                  "width":99,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c822de23ba5b4efd836d20ac1b298f14",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":438},
            "size":{
              "width":123,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 改密提示窗口",
                      "target":{
                        "targetType":"page",
                        "url":"改密提示窗口.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"68f52a23883a451cbdc06d4b21e60751",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":317,
              "y":340},
            "size":{
              "width":123,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d235a09ea8074ed2ba6c7642e5b26325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":317,
                  "y":340},
                "size":{
                  "width":123,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"545690f75fc94c61bebd0834a37f35c1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":452,
              "y":273},
            "size":{
              "width":247,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"e3fd649558eb4ffa90cc8f16d7d58993",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":452,
              "y":340},
            "size":{
              "width":247,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"298c1e99376d4eef829d0eb9be61bd29",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722dacd4e9d8409da6487b2b87f04a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u2.png"}},
{
          "id":"fdc3fd5708bd44f79ac18d1087dffe07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e8b90201aa4e8cb2c05951e04c03e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布活动",
                      "target":{
                        "targetType":"page",
                        "url":"发布活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u4.png"}},
{
          "id":"8daaf19a238c4d80888ac4ab19fd689e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0328f01f9457415bb11f7a8c851d12a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u6.png"}},
{
          "id":"a24ed69a2bf64eaeb55fa8fa9a37e37a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8be77dacb649b4b4d9bd18ba154567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u8.png"}},
{
          "id":"32ec4467162f44c8b7d16620ff082adb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c771c57710b044ec995b71167deb71fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ac106b9d7b14ca58d1714d22e91df5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e592ff2feda4ae691216dc492421cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"437eafb718284e30b783517e363218f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2342a30cd98b48f9bb3b6c95d377378a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c2500a062d948dcb25636460e86e62b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8265024db544d8a8ae5dd40b06a2e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec478d8d55774e22807a3ac468ca599b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350df4669f564df99ff106add0e930fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理主界面",
                      "target":{
                        "targetType":"page",
                        "url":"管理主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u25.png"}},
{
          "id":"d7ade81542d944a6a94699f2f2e1bad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e561bf63b34982a68a1d8e18c40dbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d2ae212cd6846e6aac330c18b7c7d71",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a81a4f973df41cbbdf6109faaee381a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u18.png"}},
{
          "id":"0e547803851b43aebf2c29825bd26c4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb0162db0b74221b831836c79f4057d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4af3d8371a114f6c89c98e782fe8b0a4":{
      "scriptId":"u0"},
    "59486f2b15734b4783006f7f3f4ae121":{
      "scriptId":"u1"},
    "98d5d96d4dd64a628f4915c4530f9e4a":{
      "scriptId":"u2"},
    "e7140c5755c245d0837b549fc5dd51ce":{
      "scriptId":"u3"},
    "c822de23ba5b4efd836d20ac1b298f14":{
      "scriptId":"u4"},
    "68f52a23883a451cbdc06d4b21e60751":{
      "scriptId":"u5"},
    "d235a09ea8074ed2ba6c7642e5b26325":{
      "scriptId":"u6"},
    "545690f75fc94c61bebd0834a37f35c1":{
      "scriptId":"u7"},
    "e3fd649558eb4ffa90cc8f16d7d58993":{
      "scriptId":"u8"},
    "298c1e99376d4eef829d0eb9be61bd29":{
      "scriptId":"u9"},
    "722dacd4e9d8409da6487b2b87f04a83":{
      "scriptId":"u10"},
    "fdc3fd5708bd44f79ac18d1087dffe07":{
      "scriptId":"u11"},
    "17e8b90201aa4e8cb2c05951e04c03e0":{
      "scriptId":"u12"},
    "8daaf19a238c4d80888ac4ab19fd689e":{
      "scriptId":"u13"},
    "0328f01f9457415bb11f7a8c851d12a3":{
      "scriptId":"u14"},
    "a24ed69a2bf64eaeb55fa8fa9a37e37a":{
      "scriptId":"u15"},
    "eb8be77dacb649b4b4d9bd18ba154567":{
      "scriptId":"u16"},
    "32ec4467162f44c8b7d16620ff082adb":{
      "scriptId":"u17"},
    "c771c57710b044ec995b71167deb71fd":{
      "scriptId":"u18"},
    "7ac106b9d7b14ca58d1714d22e91df5f":{
      "scriptId":"u19"},
    "8e592ff2feda4ae691216dc492421cb2":{
      "scriptId":"u20"},
    "437eafb718284e30b783517e363218f2":{
      "scriptId":"u21"},
    "2342a30cd98b48f9bb3b6c95d377378a":{
      "scriptId":"u22"},
    "8c2500a062d948dcb25636460e86e62b":{
      "scriptId":"u23"},
    "f8265024db544d8a8ae5dd40b06a2e83":{
      "scriptId":"u24"},
    "ec478d8d55774e22807a3ac468ca599b":{
      "scriptId":"u25"},
    "350df4669f564df99ff106add0e930fe":{
      "scriptId":"u26"},
    "d7ade81542d944a6a94699f2f2e1bad8":{
      "scriptId":"u27"},
    "93e561bf63b34982a68a1d8e18c40dbc":{
      "scriptId":"u28"},
    "4d2ae212cd6846e6aac330c18b7c7d71":{
      "scriptId":"u29"},
    "9a81a4f973df41cbbdf6109faaee381a":{
      "scriptId":"u30"},
    "0e547803851b43aebf2c29825bd26c4c":{
      "scriptId":"u31"},
    "eeb0162db0b74221b831836c79f4057d":{
      "scriptId":"u32"}}});