$axure.loadCurrentPage({
  "url":"订餐.html",
  "generationDate":new Date(1560007669858.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7613d97c2ad24f0f8b69dc2e8d556697",
    "type":"Axure:Page",
    "name":"订餐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01356c259e924fc3b94b63ca9d54e119",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":176},
            "size":{
              "width":200,
              "height":359}},
          "adaptiveStyles":{
}},
{
          "id":"01744a067f5a4c95b55cf481cc08b681",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":545},
            "size":{
              "width":90,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f268aae3d5ba4a74ba3857e2593e9edd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":545},
                "size":{
                  "width":90,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"054594d04120463f8a28d3648662e82a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":191},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"881d3c6678a54417a1d4ccf733d4de11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":191},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u3.jpg"}},
{
          "id":"45e1c8b567094fcfb7b2a6eadaae1be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":276},
            "size":{
              "width":88,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a402f4fe78284376abff52f12ecfe36c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":276},
                "size":{
                  "width":88,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8bd92ffd92d451dad926f469fd38435",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":306},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c136388d557c4517ac13d27ab983efd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":306},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u7.jpg"}},
{
          "id":"46b0f8d2b17c4009a259e0c4bc6926c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":391},
            "size":{
              "width":84,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46c3b05d8ecc4457b28a729a29d141d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":391},
                "size":{
                  "width":84,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cc4bba92c874162b8de2b9fbf3700ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":227},
            "size":{
              "width":84,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36987953a1cf4994932e690742a9d0c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":227},
                "size":{
                  "width":84,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u11.png"}},
{
          "id":"0aa6843d599b4fbcb545c1793406f9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":342},
            "size":{
              "width":84,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"010c906bc796480fb2bb277919c77d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":342},
                "size":{
                  "width":84,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订餐/u11.png"}},
{
          "id":"cd9b688072c84242a0d2bdaa2b9f5f5d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":176},
            "size":{
              "width":500,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c9b5583bb1413ab1e6c4b35528fa26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91c08d400a884ec88220decccfa3106a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"6fcf1a66aa4a4785a5d9d26c3343cf6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cda906c8a3234cbc943e25c7141d0766",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"6c94f382c4c9442a8d813bae0117a6dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc79e35f916a47d6beff3d4760a8e0c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"69fc396a3ab0401490254ac93d6d11b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":0},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46571a74dd43464fa4c427d46b869022",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":0},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"ed276a8a44154384ac3a8061b165d33f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":30},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db253994721b49a58849432bc39e705a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":30},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"410d8150e2fe4d36b01977ad30421c38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":60},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56c347f2bf684ae6aadb0110c87a30c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":60},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"ddb0cbc9ad764c94a9f45f0a92b5dacf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":0},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b13241cc211e491ea22298be1a67c772",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":0},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"4ae653bcf42840d3a32893ee478581d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":30},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"66a3d73b09994096be18c3a7d5ef9028",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":30},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"e061c0b2c9f74151a4e94e5dc4a85b92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":60},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05a822e2f85e40e7b7eb82aa850957f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":60},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"862749265f904671aae9f98aaf409d24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":330},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90d2b99f8a9b49a8925b180dab333ab3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":330},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u82.png"}},
{
              "id":"5f57200c838444869a5cf80e56f77323",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":330},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70b3ced8e7bc4c06856b120dc4d801a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":330},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u82.png"}},
{
              "id":"3614c19b5b134efa8e82e11d97a5879a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":330},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06f69b11c57c4d34b7868cb63e8ea2d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":330},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u86.png"}},
{
              "id":"1fe71dcc07f744df8f759f154abe858a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65634facd863485f8f3abeb32d29b509",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":300},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"0efbddf46b0e460fa27ee0cd7e874a74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":300},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3ffc5ad6c774cf2b06d5fde9a10ed13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":300},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"201a6815f3b043fb8c112638eede4f7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":300},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fe16211c2a84359ace761b795adf574",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":300},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"65c1c4f3fa4d45a083262c9d8c030ea9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dd20905109f4235bb86bf5586c86590",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":270},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"30bd56fc19754507a3f67628c0c32f91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":270},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8557b09ee4bf4d539379c1a3a891b983",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":270},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"e3c0d18cad4a45d4bd2bead0a0f0de39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":270},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ffd9e4d39bb64ca78e537914dd54d8bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":270},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"f629de381e4441e5af7305947a2794d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ee20758822b42e68713541a884afbf7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"2d0caa125ba045f5b42ca0e2d89d71d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":240},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71da7a363ecd43a297880f083e6073c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":240},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"9a886f9a012d4db49a5a6bb18e7f1906",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":240},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6870a8348e44c78903c102e6a1661ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":240},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"fc8990378cb94443832649930716b54a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff10421cf7a34f2693e70040ddc63057",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"44eea1647a8c473b8a3308104dd80f93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":210},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e94e8c46cd5c435fa83b58b1af39c6f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":210},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"6b92a1605fc84659bb97b60c0eba895a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":210},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"585101baebf44c64b2962656fecb3297",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":210},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"04fa59661a094fa7975d53c37ac5c0da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15f98e4df8204c2f98cc9a08481e2e0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"5d07f7800048478482d7fd160e71445a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":180},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5adae9fd488d4203bbeb2f76849bb855",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":180},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"fdbfc38978fb45eeb4f3ab2eebea7905",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":180},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e144bcec7a54b90b7ca0843307517e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":180},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"b206e5cf0a974a66bee043d6e0c13013",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cd5497e35c24ba1bf8c5319c8e63e39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"fcd5fa5ffbdf4773bb752b7cd7e01972",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":150},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa850883925e43c3900b558fd660cc13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":150},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"e8b9b3cd0ac54d5ab4ad3892cd93fbec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":150},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f59cd0da5cf4832bb0d6b13c7bbda9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":150},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"8fc91c878b2945ff8011085736a8af49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de00acfb6a2e420d891639c7464abebf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"16117c879476446a86f9d5df385cd6bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":120},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2eb8b2dd0f0b4a9daecdf353421ab64f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":120},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"0d00db42328844d6af25e618701da8dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":120},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c16fbfa8ac24705a251cdeedbf361b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":120},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}},
{
              "id":"4f8b278292084a288749d005c7f1cc0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4460ea325294026aa9b6e3613b004f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"c207ea8ff6eb4bb89754c2c69764a07b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":90},
                "size":{
                  "width":167,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"330db06f58da417cae411ab534c12e7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":90},
                    "size":{
                      "width":167,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u16.png"}},
{
              "id":"5a927cedddc2486c809a021581549721",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":334,
                  "y":90},
                "size":{
                  "width":166,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02e5bd24cc23436891f5a888217daf32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":334,
                      "y":90},
                    "size":{
                      "width":166,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订餐/u20.png"}}]},
{
          "id":"ffb29c57d34340799e1c084d7b65f29a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":238},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 当前部件",
                      "objectsToFades":[{
                          "objectPath":["ffb29c57d34340799e1c084d7b65f29a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"6b239f1cf3cc49faa0adeaf183c43289",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c70588e159c42f2a336840bbc4c6666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u2.png"}},
{
          "id":"43d55889a0d54b6281cfc776e92b6eef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b787046bb948898dcf902fcce6153f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布活动",
                      "target":{
                        "targetType":"page",
                        "url":"发布活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u4.png"}},
{
          "id":"c451200aeff949cbbef39d66bf1770c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5674e124b4b547ff90af0d8fa55988be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u6.png"}},
{
          "id":"aebc5ead84db4b49b01ed0eeeba75575",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893f917747e3439ab681ba0d74b981b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u8.png"}},
{
          "id":"f9da9dff76d54b9684c0ccf5f8409a88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1fa2952e17847e6b840a164a86de5a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a199a95b1e7043bea95348bf6ed86770",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25cc3df536e641ecb5de21da91fc90d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11f9bf7401fe499dbefcf7f2f5a4d224",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a99a5a6fc41d4344b1a6807d14c7c4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b32cd0b1155e4eaa8557588933922f3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27019a8c8ddb4aec83bca54930970808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77424e63dddb43e985aab1eb988cca4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f11bf4ce68b470a8cc02feda8846b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理主界面",
                      "target":{
                        "targetType":"page",
                        "url":"管理主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u25.png"}},
{
          "id":"3d4d8be213324bbea7b9cb8e1b732abd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ad432f4972b4df486fff2aeefcb56d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41da2fd828654b92bab542cc83dff756",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a4b436395c140a19641cce91db6cde5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u18.png"}},
{
          "id":"73deb7de233a42909f1fcc63435530ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479b3538ed8943e48d7af92bc7a980dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "01356c259e924fc3b94b63ca9d54e119":{
      "scriptId":"u0"},
    "01744a067f5a4c95b55cf481cc08b681":{
      "scriptId":"u1"},
    "f268aae3d5ba4a74ba3857e2593e9edd":{
      "scriptId":"u2"},
    "054594d04120463f8a28d3648662e82a":{
      "scriptId":"u3"},
    "881d3c6678a54417a1d4ccf733d4de11":{
      "scriptId":"u4"},
    "45e1c8b567094fcfb7b2a6eadaae1be8":{
      "scriptId":"u5"},
    "a402f4fe78284376abff52f12ecfe36c":{
      "scriptId":"u6"},
    "f8bd92ffd92d451dad926f469fd38435":{
      "scriptId":"u7"},
    "c136388d557c4517ac13d27ab983efd2":{
      "scriptId":"u8"},
    "46b0f8d2b17c4009a259e0c4bc6926c3":{
      "scriptId":"u9"},
    "46c3b05d8ecc4457b28a729a29d141d3":{
      "scriptId":"u10"},
    "4cc4bba92c874162b8de2b9fbf3700ff":{
      "scriptId":"u11"},
    "36987953a1cf4994932e690742a9d0c4":{
      "scriptId":"u12"},
    "0aa6843d599b4fbcb545c1793406f9b3":{
      "scriptId":"u13"},
    "010c906bc796480fb2bb277919c77d8d":{
      "scriptId":"u14"},
    "cd9b688072c84242a0d2bdaa2b9f5f5d":{
      "scriptId":"u15"},
    "40c9b5583bb1413ab1e6c4b35528fa26":{
      "scriptId":"u16"},
    "91c08d400a884ec88220decccfa3106a":{
      "scriptId":"u17"},
    "69fc396a3ab0401490254ac93d6d11b3":{
      "scriptId":"u18"},
    "46571a74dd43464fa4c427d46b869022":{
      "scriptId":"u19"},
    "ddb0cbc9ad764c94a9f45f0a92b5dacf":{
      "scriptId":"u20"},
    "b13241cc211e491ea22298be1a67c772":{
      "scriptId":"u21"},
    "6fcf1a66aa4a4785a5d9d26c3343cf6d":{
      "scriptId":"u22"},
    "cda906c8a3234cbc943e25c7141d0766":{
      "scriptId":"u23"},
    "ed276a8a44154384ac3a8061b165d33f":{
      "scriptId":"u24"},
    "db253994721b49a58849432bc39e705a":{
      "scriptId":"u25"},
    "4ae653bcf42840d3a32893ee478581d8":{
      "scriptId":"u26"},
    "66a3d73b09994096be18c3a7d5ef9028":{
      "scriptId":"u27"},
    "6c94f382c4c9442a8d813bae0117a6dc":{
      "scriptId":"u28"},
    "dc79e35f916a47d6beff3d4760a8e0c7":{
      "scriptId":"u29"},
    "410d8150e2fe4d36b01977ad30421c38":{
      "scriptId":"u30"},
    "56c347f2bf684ae6aadb0110c87a30c8":{
      "scriptId":"u31"},
    "e061c0b2c9f74151a4e94e5dc4a85b92":{
      "scriptId":"u32"},
    "05a822e2f85e40e7b7eb82aa850957f1":{
      "scriptId":"u33"},
    "4f8b278292084a288749d005c7f1cc0d":{
      "scriptId":"u34"},
    "c4460ea325294026aa9b6e3613b004f7":{
      "scriptId":"u35"},
    "c207ea8ff6eb4bb89754c2c69764a07b":{
      "scriptId":"u36"},
    "330db06f58da417cae411ab534c12e7b":{
      "scriptId":"u37"},
    "5a927cedddc2486c809a021581549721":{
      "scriptId":"u38"},
    "02e5bd24cc23436891f5a888217daf32":{
      "scriptId":"u39"},
    "8fc91c878b2945ff8011085736a8af49":{
      "scriptId":"u40"},
    "de00acfb6a2e420d891639c7464abebf":{
      "scriptId":"u41"},
    "16117c879476446a86f9d5df385cd6bd":{
      "scriptId":"u42"},
    "2eb8b2dd0f0b4a9daecdf353421ab64f":{
      "scriptId":"u43"},
    "0d00db42328844d6af25e618701da8dc":{
      "scriptId":"u44"},
    "5c16fbfa8ac24705a251cdeedbf361b8":{
      "scriptId":"u45"},
    "b206e5cf0a974a66bee043d6e0c13013":{
      "scriptId":"u46"},
    "0cd5497e35c24ba1bf8c5319c8e63e39":{
      "scriptId":"u47"},
    "fcd5fa5ffbdf4773bb752b7cd7e01972":{
      "scriptId":"u48"},
    "fa850883925e43c3900b558fd660cc13":{
      "scriptId":"u49"},
    "e8b9b3cd0ac54d5ab4ad3892cd93fbec":{
      "scriptId":"u50"},
    "9f59cd0da5cf4832bb0d6b13c7bbda9e":{
      "scriptId":"u51"},
    "04fa59661a094fa7975d53c37ac5c0da":{
      "scriptId":"u52"},
    "15f98e4df8204c2f98cc9a08481e2e0a":{
      "scriptId":"u53"},
    "5d07f7800048478482d7fd160e71445a":{
      "scriptId":"u54"},
    "5adae9fd488d4203bbeb2f76849bb855":{
      "scriptId":"u55"},
    "fdbfc38978fb45eeb4f3ab2eebea7905":{
      "scriptId":"u56"},
    "4e144bcec7a54b90b7ca0843307517e4":{
      "scriptId":"u57"},
    "fc8990378cb94443832649930716b54a":{
      "scriptId":"u58"},
    "ff10421cf7a34f2693e70040ddc63057":{
      "scriptId":"u59"},
    "44eea1647a8c473b8a3308104dd80f93":{
      "scriptId":"u60"},
    "e94e8c46cd5c435fa83b58b1af39c6f9":{
      "scriptId":"u61"},
    "6b92a1605fc84659bb97b60c0eba895a":{
      "scriptId":"u62"},
    "585101baebf44c64b2962656fecb3297":{
      "scriptId":"u63"},
    "f629de381e4441e5af7305947a2794d1":{
      "scriptId":"u64"},
    "0ee20758822b42e68713541a884afbf7":{
      "scriptId":"u65"},
    "2d0caa125ba045f5b42ca0e2d89d71d4":{
      "scriptId":"u66"},
    "71da7a363ecd43a297880f083e6073c2":{
      "scriptId":"u67"},
    "9a886f9a012d4db49a5a6bb18e7f1906":{
      "scriptId":"u68"},
    "d6870a8348e44c78903c102e6a1661ca":{
      "scriptId":"u69"},
    "65c1c4f3fa4d45a083262c9d8c030ea9":{
      "scriptId":"u70"},
    "6dd20905109f4235bb86bf5586c86590":{
      "scriptId":"u71"},
    "30bd56fc19754507a3f67628c0c32f91":{
      "scriptId":"u72"},
    "8557b09ee4bf4d539379c1a3a891b983":{
      "scriptId":"u73"},
    "e3c0d18cad4a45d4bd2bead0a0f0de39":{
      "scriptId":"u74"},
    "ffd9e4d39bb64ca78e537914dd54d8bc":{
      "scriptId":"u75"},
    "1fe71dcc07f744df8f759f154abe858a":{
      "scriptId":"u76"},
    "65634facd863485f8f3abeb32d29b509":{
      "scriptId":"u77"},
    "0efbddf46b0e460fa27ee0cd7e874a74":{
      "scriptId":"u78"},
    "f3ffc5ad6c774cf2b06d5fde9a10ed13":{
      "scriptId":"u79"},
    "201a6815f3b043fb8c112638eede4f7e":{
      "scriptId":"u80"},
    "9fe16211c2a84359ace761b795adf574":{
      "scriptId":"u81"},
    "862749265f904671aae9f98aaf409d24":{
      "scriptId":"u82"},
    "90d2b99f8a9b49a8925b180dab333ab3":{
      "scriptId":"u83"},
    "5f57200c838444869a5cf80e56f77323":{
      "scriptId":"u84"},
    "70b3ced8e7bc4c06856b120dc4d801a2":{
      "scriptId":"u85"},
    "3614c19b5b134efa8e82e11d97a5879a":{
      "scriptId":"u86"},
    "06f69b11c57c4d34b7868cb63e8ea2d8":{
      "scriptId":"u87"},
    "ffb29c57d34340799e1c084d7b65f29a":{
      "scriptId":"u88"},
    "6b239f1cf3cc49faa0adeaf183c43289":{
      "scriptId":"u89"},
    "7c70588e159c42f2a336840bbc4c6666":{
      "scriptId":"u90"},
    "43d55889a0d54b6281cfc776e92b6eef":{
      "scriptId":"u91"},
    "a6b787046bb948898dcf902fcce6153f":{
      "scriptId":"u92"},
    "c451200aeff949cbbef39d66bf1770c0":{
      "scriptId":"u93"},
    "5674e124b4b547ff90af0d8fa55988be":{
      "scriptId":"u94"},
    "aebc5ead84db4b49b01ed0eeeba75575":{
      "scriptId":"u95"},
    "893f917747e3439ab681ba0d74b981b0":{
      "scriptId":"u96"},
    "f9da9dff76d54b9684c0ccf5f8409a88":{
      "scriptId":"u97"},
    "a1fa2952e17847e6b840a164a86de5a0":{
      "scriptId":"u98"},
    "a199a95b1e7043bea95348bf6ed86770":{
      "scriptId":"u99"},
    "25cc3df536e641ecb5de21da91fc90d9":{
      "scriptId":"u100"},
    "11f9bf7401fe499dbefcf7f2f5a4d224":{
      "scriptId":"u101"},
    "a99a5a6fc41d4344b1a6807d14c7c4c3":{
      "scriptId":"u102"},
    "b32cd0b1155e4eaa8557588933922f3c":{
      "scriptId":"u103"},
    "27019a8c8ddb4aec83bca54930970808":{
      "scriptId":"u104"},
    "77424e63dddb43e985aab1eb988cca4c":{
      "scriptId":"u105"},
    "9f11bf4ce68b470a8cc02feda8846b5c":{
      "scriptId":"u106"},
    "3d4d8be213324bbea7b9cb8e1b732abd":{
      "scriptId":"u107"},
    "7ad432f4972b4df486fff2aeefcb56d3":{
      "scriptId":"u108"},
    "41da2fd828654b92bab542cc83dff756":{
      "scriptId":"u109"},
    "9a4b436395c140a19641cce91db6cde5":{
      "scriptId":"u110"},
    "73deb7de233a42909f1fcc63435530ad":{
      "scriptId":"u111"},
    "479b3538ed8943e48d7af92bc7a980dc":{
      "scriptId":"u112"}}});