$axure.loadCurrentPage({
  "url":"发布活动.html",
  "generationDate":new Date(1560007669747.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bb5c4c37ed34cbb92aecc861595e301",
    "type":"Axure:Page",
    "name":"发布活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"146514291db34cc09abbf2dae0edd104",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":180},
            "size":{
              "width":605,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc99fd6f0ab4f119ebe4923f1ba3cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":180},
                "size":{
                  "width":605,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布活动/u0.png"}},
{
          "id":"aad36b4d2bf547f39b37fa7842917bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":323,
              "y":212},
            "size":{
              "width":104,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae60290f42804286818aba8011bf4a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":323,
                  "y":212},
                "size":{
                  "width":104,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9d71fa0e33469d889eef72c90d584d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":323,
              "y":263},
            "size":{
              "width":107,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d7fd0b96534e7aa457e504b52aa12a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":323,
                  "y":263},
                "size":{
                  "width":107,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dabd978995634e73a1a10b4b5066e4fe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":427,
              "y":209},
            "size":{
              "width":373,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"7ea3907e65d1417d924f5c12c99250c2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":427,
              "y":263},
            "size":{
              "width":117,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"48da404cb4a74c9bb86ce992df72ce10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":684,
              "y":260},
            "size":{
              "width":117,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"6ed57e0dee224a6aa04f6a62215482fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":573,
              "y":262},
            "size":{
              "width":107,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4148f3f967477cbb278df55cc816db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":573,
                  "y":262},
                "size":{
                  "width":107,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab0f88cfe8a747b59f13ba335ea61ee5",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":320},
            "size":{
              "width":373,
              "height":160}},
          "adaptiveStyles":{
}},
{
          "id":"bef39338fb9e422ab902746ef767334f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":313,
              "y":320},
            "size":{
              "width":104,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96a43b79f1ca4a4f996446bde027de65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":313,
                  "y":320},
                "size":{
                  "width":104,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad461f1d95af4d719d2dcd45023dacf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":328,
              "y":503},
            "size":{
              "width":107,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd9cef59cc748229bf57afcdc8f7d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":328,
                  "y":503},
                "size":{
                  "width":107,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa970f7f0f454aff9c7201ca037f46b1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":432.5,
              "y":502.999969482422},
            "size":{
              "width":117,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"088245fceca942a89693744015add100",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":689.5,
              "y":499.999969482422},
            "size":{
              "width":117,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4529660a517c407d85b2d5c02750ee86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":578,
              "y":502},
            "size":{
              "width":107,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cadedfb9f2e947ee9c323e609cd66e7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":578,
                  "y":502},
                "size":{
                  "width":107,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f95c68f1af234c2581767b557e0f1a51",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":550},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"other",
                      "description":"活动发布成功！",
                      "description":"活动发布成功！",
                      "popup":{
                        "left":0,
                        "top":0,
                        "width":300,
                        "height":300,
                        "toolbar":false,
                        "scrollbars":true,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":true,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"518ce34ec6e94284a2cf7d6b9814fab4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45d27e5910404ecc98963836162eaf24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u2.png"}},
{
          "id":"8e28af2a63334d19bb9cade7676309ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c916119c0b94d90a8f1a70f8a33e440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发布活动",
                      "target":{
                        "targetType":"page",
                        "url":"发布活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u4.png"}},
{
          "id":"a44f36994f874f0bbf4e5a0006d17a69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":487,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67aeba27e58d4009822cfced820c87e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值",
                      "target":{
                        "targetType":"page",
                        "url":"充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u6.png"}},
{
          "id":"4b2693abcc59403597fcb1eb078159a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b000f89b5375457a97381ed766766fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看记录",
                      "target":{
                        "targetType":"page",
                        "url":"查看记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u8.png"}},
{
          "id":"1904c7b0f08b4224b2cb6c844508d6ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":352,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ee164163f74982bf6e51a291a5f03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":352,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ac9013c593542c99757e4147f94474c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":472,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70a4e12b2cb74bc9b8579bb8e1f6b4a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":472,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d1254ef597b455a861432d151d234f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":692,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f57906b456a4fe2b36b862774895d22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":692,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5842f44d1f39423aa1fa09c14738a30e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":582,
              "y":134},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b918120fa2024991834781ebf877e220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":582,
                  "y":134},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6b3796cb4d04d2ab1a1de1042102b75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee04d2314e5e46fb839777eed0aa176d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理主界面",
                      "target":{
                        "targetType":"page",
                        "url":"管理主界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u25.png"}},
{
          "id":"6f1e0fca396e40579eac693e645abe79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":136},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e888aea22a704090842f66893b365ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":136},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e33300b6875f45a6832ca6698983a263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":69},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa29227b9cb4608abd9bea9d15f9043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":69},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订餐",
                      "target":{
                        "targetType":"page",
                        "url":"订餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理主界面/u18.png"}},
{
          "id":"caa01334c5c444d89b0094415e4d082a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":810,
              "y":137},
            "size":{
              "width":60,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e880559f9d44f18e5909fb0c8238d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":810,
                  "y":137},
                "size":{
                  "width":60,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "146514291db34cc09abbf2dae0edd104":{
      "scriptId":"u0"},
    "7cc99fd6f0ab4f119ebe4923f1ba3cf9":{
      "scriptId":"u1"},
    "aad36b4d2bf547f39b37fa7842917bb8":{
      "scriptId":"u2"},
    "ae60290f42804286818aba8011bf4a8e":{
      "scriptId":"u3"},
    "0d9d71fa0e33469d889eef72c90d584d":{
      "scriptId":"u4"},
    "95d7fd0b96534e7aa457e504b52aa12a":{
      "scriptId":"u5"},
    "dabd978995634e73a1a10b4b5066e4fe":{
      "scriptId":"u6"},
    "7ea3907e65d1417d924f5c12c99250c2":{
      "scriptId":"u7"},
    "48da404cb4a74c9bb86ce992df72ce10":{
      "scriptId":"u8"},
    "6ed57e0dee224a6aa04f6a62215482fd":{
      "scriptId":"u9"},
    "fc4148f3f967477cbb278df55cc816db":{
      "scriptId":"u10"},
    "ab0f88cfe8a747b59f13ba335ea61ee5":{
      "scriptId":"u11"},
    "bef39338fb9e422ab902746ef767334f":{
      "scriptId":"u12"},
    "96a43b79f1ca4a4f996446bde027de65":{
      "scriptId":"u13"},
    "ad461f1d95af4d719d2dcd45023dacf0":{
      "scriptId":"u14"},
    "ffd9cef59cc748229bf57afcdc8f7d94":{
      "scriptId":"u15"},
    "aa970f7f0f454aff9c7201ca037f46b1":{
      "scriptId":"u16"},
    "088245fceca942a89693744015add100":{
      "scriptId":"u17"},
    "4529660a517c407d85b2d5c02750ee86":{
      "scriptId":"u18"},
    "cadedfb9f2e947ee9c323e609cd66e7f":{
      "scriptId":"u19"},
    "f95c68f1af234c2581767b557e0f1a51":{
      "scriptId":"u20"},
    "518ce34ec6e94284a2cf7d6b9814fab4":{
      "scriptId":"u21"},
    "45d27e5910404ecc98963836162eaf24":{
      "scriptId":"u22"},
    "8e28af2a63334d19bb9cade7676309ed":{
      "scriptId":"u23"},
    "9c916119c0b94d90a8f1a70f8a33e440":{
      "scriptId":"u24"},
    "a44f36994f874f0bbf4e5a0006d17a69":{
      "scriptId":"u25"},
    "67aeba27e58d4009822cfced820c87e9":{
      "scriptId":"u26"},
    "4b2693abcc59403597fcb1eb078159a5":{
      "scriptId":"u27"},
    "b000f89b5375457a97381ed766766fd3":{
      "scriptId":"u28"},
    "1904c7b0f08b4224b2cb6c844508d6ea":{
      "scriptId":"u29"},
    "70ee164163f74982bf6e51a291a5f03e":{
      "scriptId":"u30"},
    "3ac9013c593542c99757e4147f94474c":{
      "scriptId":"u31"},
    "70a4e12b2cb74bc9b8579bb8e1f6b4a7":{
      "scriptId":"u32"},
    "4d1254ef597b455a861432d151d234f2":{
      "scriptId":"u33"},
    "3f57906b456a4fe2b36b862774895d22":{
      "scriptId":"u34"},
    "5842f44d1f39423aa1fa09c14738a30e":{
      "scriptId":"u35"},
    "b918120fa2024991834781ebf877e220":{
      "scriptId":"u36"},
    "c6b3796cb4d04d2ab1a1de1042102b75":{
      "scriptId":"u37"},
    "ee04d2314e5e46fb839777eed0aa176d":{
      "scriptId":"u38"},
    "6f1e0fca396e40579eac693e645abe79":{
      "scriptId":"u39"},
    "e888aea22a704090842f66893b365ca9":{
      "scriptId":"u40"},
    "e33300b6875f45a6832ca6698983a263":{
      "scriptId":"u41"},
    "0aa29227b9cb4608abd9bea9d15f9043":{
      "scriptId":"u42"},
    "caa01334c5c444d89b0094415e4d082a":{
      "scriptId":"u43"},
    "67e880559f9d44f18e5909fb0c8238d8":{
      "scriptId":"u44"}}});